### ISSUE TITLE
config.xml missing raid_rank_server

### ISSUE THREAD

**Issue by elct9620** [unlightcpa/Unlight#10]
The example `config.xml` missing `raid_rank_server` and players are unable to enter Raid scene.

I think we missing this part in `config.xml`

```xml
    <raid_rank_servers>
      <set1>
      <name>localhost</name>
      <port>12070</port>
      <weight>1</weight>
      </set1>
    </raid_rank_servers>
```

**Comment by manoa-lino-chujo** [comment]
Thank you for pointing that out.
I fixed that.
