### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by elct9620** [unlightcpa/Unlight#7]
I build an XML file according to `lib/Config.as`, but I cannot log in the server after creating a new account.

The auth server always asks me to `reregist`, the problem occurs because of the matcher not correctly generate between client and server.

I am not sure the reason, but I got a different value between server and client.

**Comment by elct9620** [comment]
After some test, I found the "Session Key" is not matched between server and client. But I cannot find the reason for now.

**Comment by adslk2** [comment]
Using the file below will correct the error.

http://crypto.hurlant.com/demo/as3crypto.swc

**Comment by elct9620** [comment]
> Using the file below will correct the error.
> 
> http://crypto.hurlant.com/demo/as3crypto.swc

Thanks, I will try it later :tada:

**Comment by elct9620** [comment]
It is work 🎉
