### ISSUE TITLE
Why you use flash?

### ISSUE THREAD

**Issue by Applemann** [unlightcpa/Unlight#9]
Flash is dying technology (https://gizmodo.com/adobe-is-finally-killing-flash-for-real-this-time-1797231399).
Why you use it when you can take some good game engine?
For example Godot?? (https://godotengine.org/)

**Comment by beanels01** [comment]
Because this game is about 10 years ago.
Godot is nothing at that time.

**Comment by Karube** [comment]
> Flash is dying technology

I think so, too.

**Comment by Applemann** [comment]
Aha it tooks like that you are developing it right now..:
![Screenshot_2019-08-09 Why you use flash · Issue #9 · unlightcpa Unlight](https://user-images.githubusercontent.com/2686906/62792487-b50c7580-bacf-11e9-82cb-41d1c8415980.png)

:-)
